In [4]:
import numpy as np 
import pandas as pd

In [5]:
discount_df = pd.read_csv(r"C:\Users\Vedasri\OneDrive\Desktop\discount_shelf_life_dataset_5000.csv")

In [6]:
discount_df.head()

,product_id,product_name,product_category,freshness_score,days_since_arrival,days_to_expiry,original_price,cost_price,current_stock,daily_sales,demand_level,season,discount_percentage,remaining_shelf_life_days
0,200001,Yogurt,Dairy,0.57,6,2,67.72,52.46,304,48,low,winter,20.6,2
1,200002,Bread,Bakery,0.99,0,3,41.61,31.33,243,41,low,rainy,17.3,3
2,200003,Grapes,Fruits,0.91,1,5,121.44,93.25,60,19,medium,summer,1.8,5
3,200004,Minced Meat,Meat,0.77,3,1,318.38,205.04,174,20,low,rainy,31.8,1
4,200005,Apple,Fruits,0.84,3,9,153.66,110.23,130,36,medium,rainy,1.5,9

In [7]:
discount_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   product_id                 5000 non-null   int64
 1   product_name               5000 non-null   object
 2   product_category           5000 non-null   object
 3   freshness_score            5000 non-null   float64
 4   days_since_arrival         5000 non-null   int64
 5   days_to_expiry             5000 non-null   int64
 6   original_price             5000 non-null   float64
 7   cost_price                 5000 non-null   float64
 8   current_stock              5000 non-null   int64
 9   daily_sales                5000 non-null   int64
 10  demand_level               5000 non-null   object
 11  season                     5000 non-null   object
 12  discount_percentage        5000 non-null   float64
 13  remaining_shelf_life_days  5000 non-null   int64
dtypes: float64(4), int64(6), object(4)
memory usage: 547.0+ KB

In [8]:
discount_df.describe()

,product_id,freshness_score,days_since_arrival,days_to_expiry,original_price,cost_price,current_stock,daily_sales,discount_percentage,remaining_shelf_life_days
count,5000.000000,5000.000000,5000.000000,5000.0000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.0000
mean,202500.500000,0.774960,3.781600,5.0882,121.593508,86.061982,175.200600,45.081800,12.417940,5.0882
std,1443.520003,0.155089,4.248895,4.7220,130.701983,92.876282,72.602938,21.712674,7.922202,4.7220
min,200001.000000,0.080000,0.000000,1.0000,25.780000,15.820000,40.000000,6.000000,0.000000,1.0000
25%,201250.750000,0.690000,1.000000,2.0000,38.310000,27.587500,115.000000,27.000000,6.000000,2.0000
50%,202500.500000,0.800000,3.000000,4.0000,72.670000,51.010000,168.000000,42.000000,12.100000,4.0000
75%,203750.250000,0.890000,5.000000,6.0000,141.722500,104.020000,234.000000,63.000000,18.100000,6.0000
max,205000.000000,0.990000,27.000000,30.0000,791.420000,625.220000,319.000000,104.000000,35.000000,30.0000

In [9]:
discount_df.shape

(5000, 14)

In [10]:
discount_df.columns

Index(['product_id', 'product_name', 'product_category', 'freshness_score',
       'days_since_arrival', 'days_to_expiry', 'original_price', 'cost_price',
       'current_stock', 'daily_sales', 'demand_level', 'season',
       'discount_percentage', 'remaining_shelf_life_days'],
      dtype='object')

In [11]:
discount_df.isnull().sum()

product_id                   0
product_name                 0
product_category             0
freshness_score              0
days_since_arrival           0
days_to_expiry               0
original_price               0
cost_price                   0
current_stock                0
daily_sales                  0
demand_level                 0
season                       0
discount_percentage          0
remaining_shelf_life_days    0
dtype: int64

In [12]:
discount_df = discount_df.drop(["product_id", "product_name"], axis=1)

In [13]:
discount_df = pd.get_dummies(discount_df, drop_first=True)

In [14]:
X = discount_df.drop("discount_percentage", axis=1)
y = discount_df["discount_percentage"]

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
from sklearn.ensemble import RandomForestRegressor
model2 = RandomForestRegressor(n_estimators=200,max_depth=12,random_state=42)
model2.fit(X_train, y_train)

RandomForestRegressor(max_depth=12, n_estimators=200, random_state=42)

In [17]:
from sklearn.metrics import r2_score, mean_absolute_error
pred = model2.predict(X_test)
print("R2:", r2_score(y_test, pred))
print("MAE:", mean_absolute_error(y_test, pred))

R2: 0.9099415351942466
MAE: 1.8230349843120206

In [18]:
from sklearn.ensemble import GradientBoostingRegressor
model2 = GradientBoostingRegressor(n_estimators=200,learning_rate=0.05,max_depth=4,random_state=42)
model2.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.05, max_depth=4, n_estimators=200,
                          random_state=42)

In [19]:
pred = model2.predict(X_test)
from sklearn.metrics import r2_score, mean_absolute_error
r2 = r2_score(y_test, pred)
mae = mean_absolute_error(y_test, pred)
print("Gradient Boosting R2:", r2)
print("MAE:", mae)

Gradient Boosting R2: 0.9097499795842966
MAE: 1.8039247013899158

In [20]:
import joblib
joblib.dump(model2, "discount_model.pkl")

['discount_model.pkl']

In [21]:
freshness = joblib.load("discount_model.pkl")

In [27]:
def PredictDiscount():
    print(" Discount + Shelf Life Model – Input Based Prediction")
    print("========================================================")
    import pandas as pd
    userinpdata = pd.read_csv(r"C:\Users\Vedasri\OneDrive\Desktop\discount_shelf_life_dataset_5000.csv")
    display(userinpdata.head())
    print("\n================ Enter Input Values ================\n")
    print("Product Category:", userinpdata['product_category'].unique())
    category = input("Enter Product Category: ")
    print("\nDemand Level:", userinpdata['demand_level'].unique())
    demand = input("Enter Demand Level: ")
    print("\nSeason:", userinpdata['season'].unique())
    season = input("Enter Season: ")
    freshness = float(input(
        f"\nFreshness Score ({userinpdata.freshness_score.min()}–{userinpdata.freshness_score.max()}): "
    ))
    days_arrival = int(input(
        f"Days Since Arrival ({userinpdata.days_since_arrival.min()}–{userinpdata.days_since_arrival.max()}): "
    ))
    days_expiry = int(input(
        f"Days To Expiry ({userinpdata.days_to_expiry.min()}–{userinpdata.days_to_expiry.max()}): "
    ))
    original_price = float(input(
        f"Original Price ({userinpdata.original_price.min()}–{userinpdata.original_price.max()}): "
    ))
    cost_price = float(input(
        f"Cost Price ({userinpdata.cost_price.min()}–{userinpdata.cost_price.max()}): "
    ))
    stock = int(input(
        f"Current Stock ({userinpdata.current_stock.min()}–{userinpdata.current_stock.max()}): "
    ))
    sales = int(input(
        f"Daily Sales ({userinpdata.daily_sales.min()}–{userinpdata.daily_sales.max()}): "
    ))
    # ---- CREATE INPUT ROW ----
    row = pd.DataFrame([[ 
        category, freshness, days_arrival, days_expiry,
        original_price, cost_price, stock, sales,
        demand, season
    ]], columns=[
        'product_category', 'freshness_score', 'days_since_arrival',
        'days_to_expiry', 'original_price', 'cost_price',
        'current_stock', 'daily_sales', 'demand_level', 'season'
    ])
    print("\nGiven User Input Data:")
    display(row)
    # ---- ENCODING ----
    row_encoded = pd.get_dummies(row)
    row_encoded = row_encoded.reindex(columns=X_train.columns, fill_value=0)
    print("\n********** Prediction ***********\n")
    pred = model2.predict(row_encoded)
   # print("Raw Prediction:", pred)
    # ---- MULTI OUTPUT ----
    if hasattr(pred[0], "__len__"):
        discount = round(float(pred[0][0]), 2)
        shelf_life = round(float(pred[0][1]), 2)
        #  Final price calculation
        final_price = round(original_price - (original_price * discount / 100), 2)
        print("Recommended Discount Percentage:", discount, "%")
        print("Predicted Remaining Shelf Life Days:", shelf_life)
        print("Final Price After Discount:", final_price)
        return discount, shelf_life, final_price
    # ---- SINGLE OUTPUT ----
    else:
        discount = round(float(pred[0]), 2)
        final_price = round(original_price - (original_price * discount / 100), 2)
        print("Recommended Discount Percentage:", discount, "%")
        print("Final Price After Discount:", final_price)
        return discount, final_price

In [28]:
PredictDiscount()

 Discount + Shelf Life Model – Input Based Prediction
========================================================

,product_id,product_name,product_category,freshness_score,days_since_arrival,days_to_expiry,original_price,cost_price,current_stock,daily_sales,demand_level,season,discount_percentage,remaining_shelf_life_days
0,200001,Yogurt,Dairy,0.57,6,2,67.72,52.46,304,48,low,winter,20.6,2
1,200002,Bread,Bakery,0.99,0,3,41.61,31.33,243,41,low,rainy,17.3,3
2,200003,Grapes,Fruits,0.91,1,5,121.44,93.25,60,19,medium,summer,1.8,5
3,200004,Minced Meat,Meat,0.77,3,1,318.38,205.04,174,20,low,rainy,31.8,1
4,200005,Apple,Fruits,0.84,3,9,153.66,110.23,130,36,medium,rainy,1.5,9

================ Enter Input Values ================

Product Category: ['Dairy' 'Bakery' 'Fruits' 'Meat' 'Vegetables']

Enter Product Category:  dairy

Demand Level: ['low' 'medium' 'high']

Enter Demand Level:  high

Season: ['winter' 'rainy' 'summer']

Enter Season:  rainy

Freshness Score (0.08–0.99):  0.007
Days Since Arrival (0–27):  22
Days To Expiry (1–30):  15
Original Price (25.78–791.42):  30
Cost Price (15.82–625.22):  16.22
Current Stock (40–319):  50
Daily Sales (6–104):  8

Given User Input Data:

,product_category,freshness_score,days_since_arrival,days_to_expiry,original_price,cost_price,current_stock,daily_sales,demand_level,season
0,dairy,0.007,22,15,30.0,16.22,50,8,high,rainy

********** Prediction ***********

Recommended Discount Percentage: 17.08 %
Final Price After Discount: 24.88

(17.08, 24.88)